"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  BrainCircuit,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Columns,
  Eye,
  EyeOff,
  FileText,
  GraduationCap,
  Loader2,
  Search,
  SlidersHorizontal,
  X,
} from "lucide-react";
import type { FeedbackSummary, ReportDetail, ReviewStatus, TrainResponse } from "@/lib/api";
import { api } from "@/lib/api";
import {
  isVerified,
  PriorityBadge,
  ReviewBadge,
  REVIEW_LABELS,
  SifBadge,
} from "@/components/Badges";
import PageHeader from "@/components/PageHeader";
import ExportButton from "@/components/ExportButton";

const PRIORITIES = ["", "HIGH", "MEDIUM", "LOW"];
// "verified" is a pseudo-status = any decision an HSE professional made
// (confirmed / reviewed / edited) — handy for the queue chips.
type StatusFilter = ReviewStatus | "" | "verified";
const STATUSES: StatusFilter[] = [
  "",
  "verified",
  "pending",
  "confirmed",
  "reviewed",
  "edited",
  "rejected",
];

// Column model for the registry table — drives header sorting and the
// column visibility toggles (hidden columns are removed from the table).
type ColKey =
  | "report_id"
  | "actual_id"
  | "source"
  | "date"
  | "site"
  | "activity"
  | "sif"
  | "priority"
  | "rule"
  | "barrier"
  | "status"
  | "view";

const COLUMNS: { key: ColKey; label: string; title?: string }[] = [
  {
    key: "report_id",
    label: "Report ID",
    title: "System Report ID — generated by the platform, unique for every report",
  },
  {
    key: "actual_id",
    label: "Actual ID",
    title: "Actual ID — the report's own ID as it appeared in the imported file",
  },
  { key: "source", label: "Source file" },
  { key: "date", label: "Date" },
  { key: "site", label: "Site" },
  { key: "activity", label: "Activity" },
  { key: "sif", label: "SIF" },
  { key: "priority", label: "Priority" },
  { key: "rule", label: "Life-Saving Rule" },
  { key: "barrier", label: "Barrier Failure" },
  {
    key: "status",
    label: "Status",
    title: "HSE review state — rows the pipeline could not analyze show as failed",
  },
  { key: "view", label: "View" },
];

// All columns are enabled by default.
const DEFAULT_COLS: Record<ColKey, boolean> = COLUMNS.reduce(
  (acc, c) => ({ ...acc, [c.key]: true }),
  {} as Record<ColKey, boolean>
);

// Display name for a report source ("upload:filename.csv" -> filename).
const prettySource = (s: string | null) =>
  s
    ? s.startsWith("upload:")
      ? s.slice(7)
      : s === "demo"
        ? "Demo dataset"
        : s === "manual"
          ? "Manual entry"
          : s
    : "";
// "Modified = Y": the file's structured value replaced an AI-extracted one.
const hasModification = (r: ReportDetail) =>
  (r.analysis?.modified_fields ?? []).some((m) => m.changed);

const PRIORITY_RANK: Record<string, number> = { HIGH: 3, MEDIUM: 2, LOW: 1 };

// Shared style for the compact selects inside the filter flyouts.
const FILTER_SELECT_CLS =
  "w-full rounded-lg border border-brand-200 bg-white px-2.5 py-1.5 text-xs outline-none focus:border-brand-400";

// The three top-level filter groups. Hovering a group reveals its
// sub-filters in a panel to the right of the group (mega-menu style),
// so the toolbar stays down to three clean buttons.
type MenuKey = "report" | "details" | "review";
const FILTER_MENUS: { key: MenuKey; label: string; blurb: string }[] = [
  { key: "report", label: "Report", blurb: "File, type & SIF" },
  { key: "details", label: "Details", blurb: "Site, activity, priority…" },
  { key: "review", label: "Review", blurb: "HSE status & duplicates" },
];

export default function ReportsPage() {
  const [reports, setReports] = useState<ReportDetail[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [q, setQ] = useState("");
  const [site, setSite] = useState("");
  const [activity, setActivity] = useState("");
  const [priority, setPriority] = useState("");
  const [rule, setRule] = useState("");
  const [status, setStatus] = useState("");
  const [sif, setSif] = useState("");
  const [file, setFile] = useState("");
  const [rtype, setRtype] = useState("");
  const [hazard, setHazard] = useState("");
  const [barrier, setBarrier] = useState("");
  const [dupOnly, setDupOnly] = useState(false);

  // Table UX: per-column sort, per-column visibility, compact popovers.
  const [sortKey, setSortKey] = useState<ColKey | null>(null);
  const [sortDir, setSortDir] = useState<"asc" | "desc">("asc");
  const [colOn, setColOn] = useState<Record<ColKey, boolean>>(() => ({
    ...DEFAULT_COLS,
  }));
  const [menuOpen, setMenuOpen] = useState<MenuKey | null>(null);
  const [colsOpen, setColsOpen] = useState(false);
  const railRef = useRef<HTMLDivElement | null>(null);
  const colsRef = useRef<HTMLDivElement | null>(null);

  // Pagination: show `pageSize` rows at a time (editable from the footer).
  const [pageSize, setPageSize] = useState(2);
  const [pageState, setPageState] = useState(1);

  // Close the Filters / Columns popovers on outside click or Escape.
  useEffect(() => {
    function onDocDown(e: MouseEvent) {
      if (
        menuOpen &&
        railRef.current &&
        !railRef.current.contains(e.target as Node)
      )
        setMenuOpen(null);
      if (
        colsOpen &&
        colsRef.current &&
        !colsRef.current.contains(e.target as Node)
      )
        setColsOpen(false);
    }
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") {
        setMenuOpen(null);
        setColsOpen(false);
      }
    }
    document.addEventListener("mousedown", onDocDown);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onDocDown);
      document.removeEventListener("keydown", onKey);
    };
  }, [menuOpen, colsOpen]);

  function toggleSort(key: ColKey) {
    if (sortKey !== key) {
      setSortKey(key);
      setSortDir("asc");
    } else {
      setSortDir(sortDir === "asc" ? "desc" : "asc");
    }
  }

  function toggleCol(key: ColKey) {
    setColOn((prev) => ({ ...prev, [key]: !prev[key] }));
  }

  function enableAllCols() {
    setColOn({ ...DEFAULT_COLS });
  }

  function clearFieldFilters() {
    setSite("");
    setActivity("");
    setPriority("");
    setRule("");
    setHazard("");
    setBarrier("");
    setStatus("");
    setSif("");
    setFile("");
    setRtype("");
    setDupOnly(false);
    setMenuOpen(null);
  }

  // Human-in-the-loop: reviewed labels + "train" action.
  const [fb, setFb] = useState<FeedbackSummary | null>(null);
  const [trainBusy, setTrainBusy] = useState(false);
  const [trainResult, setTrainResult] = useState<TrainResponse | null>(null);

  useEffect(() => {
    // Support deep links: ?priority=HIGH (dashboard review queue),
    // ?file=<source> (one imported file) and ?rule=/?activity=/?hazard=/
    // ?barrier= (used by Recurring Patterns / Barrier cards to open the
    // real report set behind a pattern).
    const params = new URLSearchParams(window.location.search);
    if (params.get("priority") === "HIGH") setPriority("HIGH");
    const f = params.get("file");
    if (f) setFile(f);
    const rl = params.get("rule");
    if (rl) setRule(rl);
    const ac = params.get("activity");
    if (ac) setActivity(ac);
    const hz = params.get("hazard");
    if (hz) setHazard(hz);
    const br = params.get("barrier");
    if (br) setBarrier(br);
  }, []);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      setLoading(true);
      try {
        const data = await api.getReports({ limit: "10000" });
        if (cancelled) return;
        setReports(data);
        setError(null);
      } catch (e) {
        if (!cancelled)
          setError(e instanceof Error ? e.message : "Failed to load");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    load();
    api
      .getFeedbackSummary()
      .then(setFb)
      .catch(() => {});
    // Refresh when the user returns to the tab so imported rows appear.
    const onVisible = () => {
      if (document.visibilityState === "visible") load();
    };
    window.addEventListener("focus", onVisible);
    document.addEventListener("visibilitychange", onVisible);
    return () => {
      cancelled = true;
      window.removeEventListener("focus", onVisible);
      document.removeEventListener("visibilitychange", onVisible);
    };
  }, []);

  const rules = useMemo(() => {
    const set = new Set<string>();
    reports.forEach((r) => r.analysis?.life_saving_rule && set.add(r.analysis.life_saving_rule));
    return Array.from(set).sort();
  }, [reports]);

  // Distinct hazard + barrier values (used by the pattern deep links and the
  // filter dropdowns).
  const hazardOptions = useMemo(
    () =>
      Array.from(
        new Set(reports.map((r) => r.analysis?.hazard).filter((h): h is string => !!h))
      ).sort(),
    [reports]
  );
  const barrierOptions = useMemo(() => {
    const set = new Set<string>();
    reports.forEach((r) =>
      (r.analysis?.barrier_failure ?? []).forEach((b) => set.add(b))
    );
    return Array.from(set).sort();
  }, [reports]);

  // Report categories found in the dataset (e.g. Unsafe Act / Unsafe
  // Condition / Near Miss / Incident) — filterable like site & activity.
  const reportTypes = useMemo(
    () =>
      Array.from(
        new Set(reports.map((r) => r.report_type).filter((t): t is string => !!t))
      ).sort(),
    [reports]
  );

  // Duplicate indication: rows whose normalized text is stored more than once
  // (same incident re-reported, or a file imported twice). Cheap client-side
  // fingerprint — the report detail page adds semantic near-copy detection.
  const dupGroups = useMemo(() => {
    const byText = new Map<string, number[]>();
    const idToReport = new Map(reports.map((r) => [r.id, r]));
    for (const r of reports) {
      const key = r.report_text
        .toLowerCase()
        .replace(/[^a-z0-9\u0900-\u09ff]+/g, " ")
        .trim();
      if (key.length < 8) continue;
      const arr = byText.get(key) ?? [];
      arr.push(r.id);
      byText.set(key, arr);
    }
    const out = new Map<number, { count: number; others: string[] }>();
    for (const ids of byText.values()) {
      if (ids.length < 2) continue;
      for (const id of ids) {
        const others = ids
          .filter((x) => x !== id)
          .map((x) => idToReport.get(x)?.report_id ?? String(x));
        out.set(id, { count: ids.length, others });
      }
    }
    return out;
  }, [reports]);

  const filtered = useMemo(() => {
    return reports.filter((r) => {
      // Field search: match across the narrative, IDs, site, activity, type,
      // Life-Saving Rule and hazard — not just the report text.
      if (
        q &&
        ![
          r.report_text,
          r.report_id,
          r.source_id ?? "",
          r.site ?? "",
          r.activity ?? "",
          r.report_type ?? "",
          r.analysis?.life_saving_rule ?? "",
          r.analysis?.hazard ?? "",
        ]
          .join(" ")
          .toLowerCase()
          .includes(q.toLowerCase())
      )
        return false;
      if (rtype && (r.report_type ?? "") !== rtype) return false;
      if (dupOnly && !dupGroups.has(r.id)) return false;
      if (site && r.site !== site) return false;
      if (activity && (r.analysis?.activity ?? r.activity) !== activity) return false;
      if (hazard && r.analysis?.hazard !== hazard) return false;
      if (barrier) {
        const hits = (r.analysis?.barrier_failure ?? []).some((b) =>
          b.toLowerCase().includes(barrier.toLowerCase())
        );
        if (!hits) return false;
      }
      if (priority && r.analysis?.priority !== priority) return false;
      if (rule && r.analysis?.life_saving_rule !== rule) return false;
      if (status === "verified") {
        if (!isVerified(r.review_status)) return false;
      } else if (status && r.review_status !== status) return false;
      if (file && r.source !== file) return false;
      if (sif === "true" && !r.analysis?.sif_potential) return false;
      if (sif === "false" && r.analysis?.sif_potential) return false;
      return true;
    });
  }, [reports, q, site, activity, hazard, barrier, priority, rule, status, sif, file, rtype, dupOnly, dupGroups]);

  // Value used to sort each column, so badges order naturally (HIGH before
  // MEDIUM, SIF before non-SIF, duplicates by how many copies exist…).
  function sortValue(r: ReportDetail, key: ColKey): string | number {
    switch (key) {
      case "report_id":
        return r.report_id;
      case "actual_id":
        return r.source_id ?? "";
      case "source":
        return prettySource(r.source);
      case "date":
        return r.date ?? "";
      case "site":
        return r.site ?? "";
      case "activity":
        return r.activity ?? r.analysis?.activity ?? "";
      case "sif":
        return r.analysis?.sif_potential ? 1 : 0;
      case "priority":
        return PRIORITY_RANK[r.analysis?.priority ?? ""] ?? 0;
      case "rule":
        return r.analysis?.life_saving_rule ?? "";
      case "barrier":
        return (r.analysis?.barrier_failure ?? []).join(", ");
      case "status":
        return r.processing_status === "failed"
          ? "zz-analysis-failed"
          : r.review_status;
      case "view":
        return "";
    }
  }

  // Client-side sorting — click a header to toggle asc/desc.
  const sorted = useMemo(() => {
    if (!sortKey) return filtered;
    const dir = sortDir === "asc" ? 1 : -1;
    const key = sortKey;
    return [...filtered].sort((a, b) => {
      const va = sortValue(a, key);
      const vb = sortValue(b, key);
      let cmp: number;
      if (typeof va === "number" && typeof vb === "number") cmp = va - vb;
      else
        cmp = String(va).localeCompare(String(vb), undefined, {
          numeric: true,
          sensitivity: "base",
        });
      return cmp * dir;
    });
  }, [filtered, sortKey, sortDir]);

  const files = useMemo(
    () =>
      Array.from(
        new Map(
          reports
            .filter((r) => r.source)
            .map((r) => [r.source, r.source as string])
        ).values()
      ).sort((a, b) => a.localeCompare(b)),
    [reports]
  );
  const sites = useMemo(
    () =>
      Array.from(
        new Set(reports.map((r) => r.site).filter((s): s is string => !!s))
      ).sort(),
    [reports]
  );
  const activities = useMemo(
    () =>
      Array.from(
        new Set(
          reports
            .map((r) => r.analysis?.activity ?? r.activity)
            .filter((a): a is string => !!a)
        )
      ).sort(),
    [reports]
  );
  const counts = useMemo(
    () => ({
      total: reports.length,
      sif: reports.filter((r) => r.analysis?.sif_potential).length,
      high: reports.filter((r) => r.analysis?.priority === "HIGH").length,
      // "Needs HSE review" only counts analyzed rows without a decision;
      // rows the pipeline failed to analyze are shown separately.
      pending: reports.filter(
        (r) => r.processing_status === "analyzed" && r.review_status === "pending"
      ).length,
      verified: reports.filter((r) => isVerified(r.review_status)).length,
      rejected: reports.filter((r) => r.review_status === "rejected").length,
      duplicates: reports.filter((r) => dupGroups.has(r.id)).length,
    }),
    [reports, dupGroups]
  );

  // Quick-review shortcuts — each sets one view and clears the others.
  function setView(
    view: "all" | "sif" | "high" | "pending" | "verified" | "rejected" | "duplicates",
  ) {
    setQ("");
    setDupOnly(false);
    if (view === "all") {
      setSif("");
      setPriority("");
      setStatus("");
    } else if (view === "sif") {
      setSif("true");
      setPriority("");
      setStatus("");
    } else if (view === "high") {
      setSif("");
      setPriority("HIGH");
      setStatus("");
    } else if (view === "verified") {
      setSif("");
      setPriority("");
      setStatus("verified");
    } else if (view === "rejected") {
      setSif("");
      setPriority("");
      setStatus("rejected");
    } else {
      setSif("");
      setPriority("");
      setStatus("pending");
    }
  }

  async function trainOnLabels() {
    setTrainBusy(true);
    setTrainResult(null);
    try {
      const res = await api.trainOnFeedback();
      setTrainResult(res);
      setFb(await api.getFeedbackSummary());
      // Re-fetch so review counts stay fresh after labels are consumed.
      const data = await api.getReports({ limit: "10000" });
      setReports(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Training failed");
    } finally {
      setTrainBusy(false);
    }
  }

  // Per-column cell renderer — the tbody renders only the enabled columns.
  function cellCls(key: ColKey) {
    switch (key) {
      case "report_id":
      case "source":
      case "sif":
      case "priority":
      case "status":
      case "view":
        return "px-4 py-3";
      default:
        return "px-4 py-3 text-xs text-ink-soft";
    }
  }

  function renderCell(r: ReportDetail, key: ColKey) {
    switch (key) {
      case "report_id":
        return (
          <>
            <Link
              href={`/reports/${r.id}`}
              title={`System Report ID ${r.report_id} — opens this report`}
              className="font-mono text-xs font-semibold text-brand-700 hover:underline"
            >
              {r.report_id}
            </Link>
            {r.is_demo && (
              <span className="ml-2 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-bold uppercase text-amber-700">
                demo
              </span>
            )}
          </>
        );
      case "actual_id":
        return r.source_id ? (
          <span
            className="font-mono font-semibold text-ink"
            title={`Actual ID — this report's own ID in its source file (${prettySource(r.source)})`}
          >
            {r.source_id}
          </span>
        ) : (
          <span className="text-ink-muted">—</span>
        );
      case "source":
        return r.source ? (
          <button
            type="button"
            onClick={() => setFile(file === r.source ? "" : r.source!)}
            title={
              file === r.source
                ? "Showing only this file — click again to show all files"
                : `View all reports imported from ${prettySource(r.source)}`
            }
            aria-pressed={file === r.source}
            className={`inline-flex max-w-[170px] items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-semibold transition ${
              file === r.source
                ? "border-brand-600 bg-brand-600 text-white"
                : "border-brand-200 bg-brand-50 text-brand-700 hover:border-brand-400 hover:bg-brand-100"
            }`}
          >
            <FileText size={10} className="flex-shrink-0" />
            <span className="truncate">{prettySource(r.source)}</span>
          </button>
        ) : (
          <span className="text-xs text-ink-muted">—</span>
        );
      case "date":
        return <>{r.date ?? "—"}</>;
      case "site":
        return <>{r.site ?? "—"}</>;
      case "activity":
        return <>{r.activity ?? r.analysis?.activity ?? "—"}</>;
      case "sif":
        return <SifBadge sif={r.analysis?.sif_potential ?? false} />;
      case "priority":
        return <PriorityBadge priority={r.analysis?.priority ?? null} />;
      case "rule":
        return <>{r.analysis?.life_saving_rule ?? "—"}</>;
      case "barrier":
        return (
          <>
            {r.analysis?.barrier_failure?.length
              ? r.analysis.barrier_failure.slice(0, 2).join(", ")
              : "—"}
          </>
        );
      case "status":
        return r.processing_status === "failed" ? (
          <span
            className="status-pill status-pill-rejected"
            title="The AI pipeline could not analyze this row — open it, check the raw text and re-run the analysis"
          >
            <span className="status-dot status-dot-rejected" aria-hidden />
            Analysis failed
          </span>
        ) : (
          <ReviewBadge status={r.review_status} />
        );
      case "view":
        return (
          <Link
            href={`/reports/${r.id}`}
            className="inline-flex items-center gap-1.5 rounded-lg border border-brand-200 bg-white px-3 py-1.5 text-xs font-semibold text-brand-700 shadow-sm transition hover:border-brand-300 hover:bg-brand-50"
          >
            <Eye size={12} /> View
          </Link>
        );
      default:
        return null;
    }
  }

  const viewAll =
    sif === "" && priority === "" && status === "" && q === "";
  const viewSif = sif === "true" && priority === "" && status === "";
  const viewHigh = priority === "HIGH" && sif === "" && status === "";
  const viewPending = status === "pending" && sif === "" && priority === "";
  const viewVerified = status === "verified" && sif === "" && priority === "";
  const viewRejected = status === "rejected" && sif === "" && priority === "";

  // How many field filters are currently active (shown on the Filters button)
  // and how many columns the user disabled (hidden from the table).
  const activeFilterCount =
    [
      site,
      activity,
      priority,
      rule,
      hazard,
      barrier,
      status,
      sif,
      file,
      rtype,
    ].filter(Boolean).length + (dupOnly ? 1 : 0);
  const hiddenColCount = COLUMNS.filter((c) => !colOn[c.key]).length;
  const visibleColCount = COLUMNS.length - hiddenColCount;

  // Active field filters as removable chips — the × clears just that filter.
  const chips: { id: string; label: string; clear: () => void }[] = [];
  if (site)
    chips.push({ id: "site", label: `Site: ${site}`, clear: () => setSite("") });
  if (activity)
    chips.push({
      id: "activity",
      label: `Activity: ${activity}`,
      clear: () => setActivity(""),
    });
  if (priority)
    chips.push({
      id: "priority",
      label: `Priority: ${priority}`,
      clear: () => setPriority(""),
    });
  if (rule)
    chips.push({ id: "rule", label: `Rule: ${rule}`, clear: () => setRule("") });
  if (hazard)
    chips.push({
      id: "hazard",
      label: `Hazard: ${hazard}`,
      clear: () => setHazard(""),
    });
  if (barrier)
    chips.push({
      id: "barrier",
      label: `Barrier: ${barrier}`,
      clear: () => setBarrier(""),
    });
  if (status)
    chips.push({
      id: "status",
      label: `Status: ${
        status === "verified"
          ? "HSE checked (any)"
          : (REVIEW_LABELS[status as ReviewStatus] ?? status)
      }`,
      clear: () => setStatus(""),
    });
  if (sif)
    chips.push({
      id: "sif",
      label: `SIF: ${sif === "true" ? "Yes" : "No"}`,
      clear: () => setSif(""),
    });
  if (rtype)
    chips.push({
      id: "rtype",
      label: `Type: ${rtype}`,
      clear: () => setRtype(""),
    });
  if (file)
    chips.push({
      id: "file",
      label: `File: ${prettySource(file)}`,
      clear: () => setFile(""),
    });
  if (dupOnly)
    chips.push({
      id: "dup",
      label: "Duplicates only",
      clear: () => setDupOnly(false),
    });

  // Pagination over the filtered set — the page resets whenever the data
  // (filters / search / reload) or the page size changes.
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const page = Math.min(pageState, totalPages);
  const start = (page - 1) * pageSize;
  const pageRows = sorted.slice(start, start + pageSize);
  useEffect(() => {
    setPageState(1);
  }, [filtered.length, pageSize]);

  // Export exactly what the user sees (filters + search applied). The system
  // Report ID and the file's Actual ID stay distinct, and the Status column is
  // explicit — rows the pipeline could not analyze are not shown as "pending".
  const exportRows = filtered.map((r) => ({
    "Report ID": r.report_id,
    "Actual ID (file)": r.source_id ?? "",
    "Source File": prettySource(r.source),
    Status:
      r.processing_status === "failed"
        ? "Analysis failed"
        : REVIEW_LABELS[r.review_status],
    "Modified (Y/N)": hasModification(r) ? "Y" : "N",
    Date: r.date ?? "",
    Type: r.report_type ?? "",
    Site: r.site ?? "",
    Activity: r.activity ?? r.analysis?.activity ?? "",
    "SIF-potential": r.analysis?.sif_potential ?? false,
    "Confidence (%)":
      r.analysis?.confidence != null ? Math.round(r.analysis.confidence * 100) : "",
    Priority: r.analysis?.priority ?? "",
    "Life-Saving Rule": r.analysis?.life_saving_rule ?? "",
    "Barrier Failure": r.analysis?.barrier_failure ?? [],
    Hazard: r.analysis?.hazard ?? "",
    "Report Text": r.report_text,
  }));

  return (
    <div className="animate-rise">
      <PageHeader
        kicker="Report Registry"
        title="SIF Reports"
        icon={FileText}
        lede="Every analyzed report — searchable, filterable, and ready for HSE review. Click any report to see the AI analysis with evidence and to confirm or correct the result."
        actions={
          <ExportButton
            rows={exportRows}
            filename="sif-reports"
            label="Export CSV"
          />
        }
      />

      {/* Review shortcuts */}
      <div className="mb-4 flex flex-wrap items-center gap-2">
        <span className="mr-1 text-[11px] font-bold uppercase tracking-wider text-ink-muted">
          Review queue:
        </span>
        <FilterChip
          active={viewAll}
          onClick={() => setView("all")}
          label="All reports"
          count={counts.total}
        />
        <FilterChip
          active={viewSif}
          onClick={() => setView("sif")}
          label="SIF-potential"
          count={counts.sif}
          pink
        />
        <FilterChip
          active={viewHigh}
          onClick={() => setView("high")}
          label="High priority"
          count={counts.high}
          red
        />
        <FilterChip
          active={viewPending}
          onClick={() => setView("pending")}
          label="Pending HSE review"
          count={counts.pending}
          amber
        />
        <FilterChip
          active={viewVerified}
          onClick={() => setView("verified")}
          label="HSE verified"
          count={counts.verified}
          green
        />
        <FilterChip
          active={viewRejected}
          onClick={() => setView("rejected")}
          label="Rejected · not SIF"
          count={counts.rejected}
          orange
        />
        <FilterChip
          active={dupOnly}
          onClick={() => {
            if (dupOnly) {
              setDupOnly(false);
            } else {
              setView("all");
              setDupOnly(true);
            }
          }}
          label="Possible duplicates"
          count={counts.duplicates}
          violet
        />
        {!viewAll && (
          <button
            onClick={() => setView("all")}
            className="text-xs font-semibold text-brand-700 hover:underline"
          >
            Clear filters
          </button>
        )}

        {/* Human-in-the-loop training */}
        <div className="ml-auto flex items-center gap-2">
          <button
            onClick={trainOnLabels}
            disabled={trainBusy || (fb?.labeled_for_training ?? 0) === 0}
            title="Re-measure model-vs-human agreement and learn signals from reviewed labels"
            className="inline-flex items-center gap-1.5 rounded-full border border-violet-200 bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-700 transition hover:bg-violet-100 disabled:cursor-not-allowed disabled:opacity-40"
          >
            {trainBusy ? (
              <Loader2 size={13} className="animate-spin" />
            ) : (
              <GraduationCap size={13} />
            )}
            Train on {fb?.labeled_for_training ?? 0} reviewed label
            {(fb?.labeled_for_training ?? 0) === 1 ? "" : "s"}
          </button>
          {fb && fb.feedback_count > 0 && (
            <span className="hidden text-[11px] text-ink-muted sm:inline">
              {fb.feedback_count} review{fb.feedback_count === 1 ? "" : "s"} stored
            </span>
          )}
        </div>
      </div>

      {fb?.latest_run && !trainResult && (
        <p className="mb-4 flex items-start gap-2 rounded-xl border border-violet-100 bg-violet-50/60 px-3.5 py-2.5 text-xs text-ink-soft">
          <BrainCircuit size={14} className="mt-0.5 flex-shrink-0 text-violet-600" />
          <span>
            <b className="text-violet-800">Latest training run:</b>{" "}
            {fb?.latest_run ? `${fb.latest_run.feedback_count} labels · agreement ${Math.round((fb.latest_run.metrics?.accuracy ?? 0) * 100)}% · F1 ${(fb.latest_run.metrics?.f1 ?? 0).toFixed(2)}` : "—"}
          </span>
        </p>
      )}
      {trainResult && (
        <div className="mb-4 flex flex-wrap items-start gap-x-4 gap-y-1 rounded-xl border border-violet-200 bg-violet-50 px-4 py-3 text-xs text-ink-soft">
          <span className="inline-flex items-center gap-1.5 font-bold text-violet-800">
            <GraduationCap size={14} /> Training run #{trainResult.run_id}
          </span>
          <span>
            Labels: <b>{trainResult.feedback_count}</b>
          </span>
          <span>
            AI ↔ HSE agreement: <b>{trainResult.human_model_agreement}%</b>
          </span>
          <span>
            Precision <b>{trainResult.metrics.precision.toFixed(2)}</b> · Recall{" "}
            <b>{trainResult.metrics.recall.toFixed(2)}</b> · F1{" "}
            <b>{trainResult.metrics.f1.toFixed(2)}</b>
          </span>
          <span className="w-full text-violet-700">
            {trainResult.signals.length > 0 ? (
              <>
                Learned {trainResult.signals.length} signal
                {trainResult.signals.length === 1 ? "" : "s"} — future analyses
                quote them and flag for review (verdict never auto-flips):{" "}
                {trainResult.signals.slice(0, 3).map((s) => `“${s.phrase}”`).join(", ")}
                {trainResult.signals.length > 3 ? "…" : ""}
              </>
            ) : (
              "No new signals this run — reviewed labels agreed with the model."
            )}
          </span>
        </div>
      )}

      <div className="card">
        {/* Toolbar: search + compact Filters / Columns controls */}
        <div className="flex flex-wrap items-center gap-2">
          <div className="relative min-w-[220px] flex-1">
            <Search
              size={15}
              className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-muted"
            />
            <input
              value={q}
              onChange={(e) => setQ(e.target.value)}
              placeholder="Search text, ID, site, activity, rule…"
              className="w-full rounded-xl border border-brand-200 bg-white py-2.5 pl-9 pr-3 text-sm outline-none focus:border-brand-400"
            />
          </div>

          {/* Filters — three top-level groups; hovering reveals the
              sub-filters in a panel to the right of the group */}
          <div className="relative" ref={railRef}>
            <div className="flex flex-wrap items-center gap-1.5">
              {FILTER_MENUS.map((m) => {
                const open = menuOpen === m.key;
                const activeCount =
                  m.key === "report"
                    ? [file, rtype, sif].filter(Boolean).length
                    : m.key === "details"
                      ? [site, activity, priority, rule, hazard, barrier].filter(Boolean).length
                      : [status, dupOnly ? "dup" : ""].filter(Boolean).length;
                return (
                  <div
                    key={m.key}
                    className="relative"
                    onMouseEnter={() => setMenuOpen(m.key)}
                    onMouseLeave={() => setMenuOpen(null)}
                  >
                    <button
                      type="button"
                      onClick={() => setMenuOpen(open ? null : m.key)}
                      aria-expanded={open}
                      className={`inline-flex items-center gap-1.5 rounded-xl border px-3 py-2.5 text-sm font-semibold transition ${
                        open || activeCount > 0
                          ? "border-brand-500 bg-brand-50 text-brand-700"
                          : "border-brand-200 bg-white text-ink-soft hover:border-brand-300 hover:bg-brand-50"
                      }`}
                    >
                      {m.label}
                      {activeCount > 0 && (
                        <span className="rounded-full bg-brand-600 px-1.5 text-[10px] font-bold leading-4 text-white">
                          {activeCount}
                        </span>
                      )}
                      <ChevronDown
                        size={14}
                        className={`transition-transform ${
                          open ? "rotate-180" : ""
                        }`}
                      />
                    </button>

                    {/* Flush against the button (no gap) so the hover path
                        from the group button into the flyout never closes it. */}
                    {open && (
                      <div className="absolute left-full top-0 z-30 w-64 rounded-r-xl rounded-l-none border border-brand-100 bg-white p-3 shadow-soft">
                        {m.key === "report" && (
                          <div className="space-y-2.5">
                            <FilterSelect
                              label="Source file"
                              value={file}
                              onChange={setFile}
                              options={files.map((f) => ({
                                value: f,
                                label: prettySource(f),
                              }))}
                              allLabel="All files"
                            />
                            <FilterSelect
                              label="Report type"
                              value={rtype}
                              onChange={setRtype}
                              options={reportTypes.map((t) => ({
                                value: t,
                                label: t,
                              }))}
                              allLabel="All types"
                            />
                            <FilterSelect
                              label="SIF-potential"
                              value={sif}
                              onChange={setSif}
                              options={[
                                { value: "true", label: "SIF: Yes" },
                                { value: "false", label: "SIF: No" },
                              ]}
                              allLabel="SIF: All"
                            />
                          </div>
                        )}
                        {m.key === "details" && (
                          <div className="space-y-2.5">
                            <FilterSelect
                              label="Site"
                              value={site}
                              onChange={setSite}
                              options={sites.map((s) => ({ value: s, label: s }))}
                              allLabel="All sites"
                            />
                            <FilterSelect
                              label="Activity"
                              value={activity}
                              onChange={setActivity}
                              options={activities.map((a) => ({
                                value: a,
                                label: a,
                              }))}
                              allLabel="All activities"
                            />
                            <FilterSelect
                              label="Priority"
                              value={priority}
                              onChange={setPriority}
                              options={PRIORITIES.filter(Boolean).map((p) => ({
                                value: p,
                                label: p,
                              }))}
                              allLabel="All priorities"
                            />
                            <FilterSelect
                              label="Life-saving rule"
                              value={rule}
                              onChange={setRule}
                              options={rules.map((r) => ({ value: r, label: r }))}
                              allLabel="All rules"
                            />
                            <FilterSelect
                              label="Hazard"
                              value={hazard}
                              onChange={setHazard}
                              options={hazardOptions.map((h) => ({
                                value: h,
                                label: h,
                              }))}
                              allLabel="All hazards"
                            />
                            <FilterSelect
                              label="Barrier failure"
                              value={barrier}
                              onChange={setBarrier}
                              options={barrierOptions.map((b) => ({
                                value: b,
                                label: b,
                              }))}
                              allLabel="All barrier failures"
                            />
                          </div>
                        )}
                        {m.key === "review" && (
                          <div className="space-y-2.5">
                            <FilterSelect
                              label="HSE status"
                              value={status}
                              onChange={setStatus}
                              options={STATUSES.filter(Boolean).map((s) => ({
                                value: s,
                                label:
                                  s === "verified"
                                    ? "HSE checked (any)"
                                    : (REVIEW_LABELS[s as ReviewStatus] ?? s),
                              }))}
                              allLabel="All statuses"
                            />
                            <div>
                              <span className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-ink-muted">
                                Duplicates
                              </span>
                              <button
                                type="button"
                                onClick={() => setDupOnly((v) => !v)}
                                aria-pressed={dupOnly}
                                className={`flex w-full items-center gap-2 rounded-lg border px-2.5 py-2 text-xs font-semibold transition ${
                                  dupOnly
                                    ? "border-brand-600 bg-brand-50 text-brand-700"
                                    : "border-brand-200 bg-white text-ink-soft hover:border-brand-300 hover:bg-brand-50"
                                }`}
                              >
                                <span
                                  className={`flex h-4 w-4 flex-shrink-0 items-center justify-center rounded border transition ${
                                    dupOnly
                                      ? "border-brand-600 bg-brand-600 text-white"
                                      : "border-brand-300 bg-white text-transparent"
                                  }`}
                                >
                                  <Check size={12} strokeWidth={3} />
                                </span>
                                Only duplicates ({dupGroups.size} rows)
                              </button>
                            </div>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Columns — enable/disable any column; hidden ones disappear */}
          <div className="relative" ref={colsRef}>
            <button
              type="button"
              onClick={() => {
                setColsOpen((v) => !v);
                setMenuOpen(null);
              }}
              className={`inline-flex items-center gap-1.5 rounded-xl border px-3 py-2.5 text-sm font-semibold transition ${
                colsOpen
                  ? "border-brand-500 bg-brand-50 text-brand-700"
                  : "border-brand-200 bg-white text-ink-soft hover:border-brand-300 hover:bg-brand-50"
              }`}
            >
              <Columns size={15} />
              Columns
              {hiddenColCount > 0 && (
                <span className="rounded-full bg-ink px-1.5 text-[10px] font-bold leading-4 text-white">
                  {hiddenColCount}
                </span>
              )}
              <ChevronDown
                size={14}
                className={`transition-transform ${
                  colsOpen ? "rotate-180" : ""
                }`}
              />
            </button>

            {colsOpen && (
              <div className="absolute right-0 z-30 mt-2 w-64 rounded-xl border border-brand-100 bg-white p-3 shadow-soft">
                <div className="mb-1 flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-ink-muted">
                    Visible columns
                  </span>
                  {hiddenColCount > 0 && (
                    <button
                      type="button"
                      onClick={enableAllCols}
                      className="text-xs font-semibold text-brand-700 hover:underline"
                    >
                      Show all
                    </button>
                  )}
                </div>
                <ul className="max-h-72 space-y-0.5 overflow-y-auto py-1">
                  {COLUMNS.map((c) => {
                    const on = colOn[c.key];
                    return (
                      <li key={c.key}>
                        <button
                          type="button"
                          onClick={() => toggleCol(c.key)}
                          className={`flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-left text-xs font-semibold transition ${
                            on
                              ? "text-ink hover:bg-brand-50"
                              : "text-ink-muted hover:bg-brand-50"
                          }`}
                        >
                          <span
                            className={`flex h-4 w-4 flex-shrink-0 items-center justify-center rounded border transition ${
                              on
                                ? "border-brand-600 bg-brand-600 text-white"
                                : "border-brand-300 bg-white text-transparent"
                            }`}
                          >
                            <Check size={12} strokeWidth={3} />
                          </span>
                          <span
                            className={`truncate ${
                              on ? "" : "opacity-70 line-through"
                            }`}
                          >
                            {c.label}
                          </span>
                          {on ? (
                            <Eye
                              size={13}
                              className="ml-auto flex-shrink-0 text-brand-500"
                            />
                          ) : (
                            <EyeOff
                              size={13}
                              className="ml-auto flex-shrink-0 text-ink-muted/70"
                            />
                          )}
                        </button>
                      </li>
                    );
                  })}
                </ul>
                <p className="mt-1 border-t border-brand-100 pt-2 text-[10px] leading-snug text-ink-muted">
                  Hidden columns are removed from the table — re-enable them
                  here anytime.
                </p>
              </div>
            )}
          </div>

          <div className="ml-auto flex items-center gap-1.5 text-xs text-ink-muted">
            <SlidersHorizontal size={13} />
            {sorted.length} of {reports.length} reports
          </div>
        </div>

        {/* Applied filters — visible chips; × removes just that filter */}
        {chips.length > 0 && (
          <div className="mt-3 flex flex-wrap items-center gap-1.5">
            <span className="mr-0.5 text-[11px] font-bold uppercase tracking-wider text-ink-muted">
              Filters:
            </span>
            {chips.map((c) => (
              <span
                key={c.id}
                className="inline-flex items-center gap-1.5 rounded-full border border-brand-300 bg-brand-50 py-1 pl-3 pr-1 text-xs font-semibold text-brand-700"
              >
                {c.label}
                <button
                  type="button"
                  onClick={c.clear}
                  title={`Remove filter: ${c.label}`}
                  aria-label={`Remove filter: ${c.label}`}
                  className="flex h-4 w-4 items-center justify-center rounded-full bg-brand-200/70 text-brand-800 transition hover:bg-brand-300 hover:text-white"
                >
                  <X size={11} strokeWidth={3} />
                </button>
              </span>
            ))}
            <button
              type="button"
              onClick={clearFieldFilters}
              className="rounded-full px-2 py-1 text-xs font-semibold text-ink-muted transition hover:bg-brand-50 hover:text-brand-700"
            >
              Clear all
            </button>
          </div>
        )}

        {error && (
          <div className="mt-4 flex items-start gap-2 rounded-xl border border-red-200 bg-red-50 p-3.5 text-sm text-red-700">
            <AlertTriangle size={16} className="mt-0.5 flex-shrink-0" /> {error}
          </div>
        )}

        <div className="table-wrap mt-4">
          <table className="w-full min-w-[880px] text-left text-sm">
            <thead>
              <tr className="table-head">
                {COLUMNS.filter((c) => colOn[c.key]).map((c) => {
                  const active = sortKey === c.key;
                  return (
                    <th
                      key={c.key}
                      title={c.title}
                      className="px-4 py-3 font-semibold"
                    >
                      <button
                        type="button"
                        onClick={() => toggleSort(c.key)}
                        title={`${c.title ? `${c.title}. ` : ""}${
                          active
                            ? `Sorted ${sortDir === "asc" ? "ascending" : "descending"} — click to reverse`
                            : `Click to sort by ${c.label.toLowerCase()}`
                        }`}
                        className="inline-flex items-center gap-1 whitespace-nowrap uppercase tracking-wider transition select-none"
                      >
                        {c.label}
                        {active ? (
                          sortDir === "asc" ? (
                            <ArrowUp size={12} className="text-brand-500" />
                          ) : (
                            <ArrowDown size={12} className="text-brand-500" />
                          )
                        ) : (
                          <ArrowUpDown
                            size={12}
                            className="text-ink-muted/50"
                          />
                        )}
                      </button>
                    </th>
                  );
                })}
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan={visibleColCount} className="px-4 py-12 text-center">
                    <Loader2 className="mx-auto animate-spin text-brand-500" size={24} />
                  </td>
                </tr>
              ) : filtered.length === 0 ? (
                <tr>
                  <td colSpan={visibleColCount} className="px-4 py-12 text-center text-sm text-ink-muted">
                    No reports match the current filters.
                  </td>
                </tr>
              ) : (
                pageRows.map((r) => (
                  <tr key={r.id} className="table-row">
                    {COLUMNS.filter((c) => colOn[c.key]).map((c) => (
                      <td key={c.key} className={cellCls(c.key)}>
                        {renderCell(r, c.key)}
                      </td>
                    ))}
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Table footer — editable "50 of N records" + page navigation */}
        <div className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-brand-100 bg-white px-4 py-2.5">
          <div className="flex flex-wrap items-center gap-2 text-xs text-ink-muted">
            <PageSizeEditor
              value={pageSize}
              max={Math.max(reports.length, 1)}
              onCommit={(n) => {
                setPageSize(n);
                setPageState(1);
              }}
            />
            <span>of {reports.length} records</span>
            {filtered.length !== reports.length && (
              <span className="text-ink-muted/70">
                · {filtered.length} match the current filters
              </span>
            )}
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => setPageState(Math.max(1, page - 1))}
              disabled={page <= 1}
              className="inline-flex items-center gap-1 rounded-lg border border-brand-200 bg-white px-2.5 py-1.5 text-xs font-semibold text-ink-soft transition hover:border-brand-300 hover:bg-brand-50 disabled:cursor-not-allowed disabled:opacity-40"
            >
              <ChevronLeft size={13} /> Prev
            </button>
            <span className="px-1 text-xs font-semibold text-ink-soft">
              Page {page} of {totalPages}
            </span>
            <button
              type="button"
              onClick={() => setPageState(Math.min(totalPages, page + 1))}
              disabled={page >= totalPages}
              className="inline-flex items-center gap-1 rounded-lg border border-brand-200 bg-white px-2.5 py-1.5 text-xs font-semibold text-ink-soft transition hover:border-brand-300 hover:bg-brand-50 disabled:cursor-not-allowed disabled:opacity-40"
            >
              Next <ChevronRight size={13} />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function FilterChip({
  label,
  count,
  active,
  onClick,
  pink,
  red,
  amber,
  green,
  orange,
  violet,
}: {
  label: string;
  count: number;
  active: boolean;
  onClick: () => void;
  pink?: boolean;
  red?: boolean;
  amber?: boolean;
  green?: boolean;
  orange?: boolean;
  violet?: boolean;
}) {
  const activeTone = pink
    ? "border-brand-600 bg-brand-600 text-white shadow-sm"
    : red
      ? "border-red-600 bg-red-600 text-white shadow-sm"
      : amber
        ? "border-amber-500 bg-amber-500 text-white shadow-sm"
        : green
          ? "border-green-600 bg-green-600 text-white shadow-sm"
          : orange
            ? "border-orange-600 bg-orange-600 text-white shadow-sm"
            : violet
              ? "border-violet-600 bg-violet-600 text-white shadow-sm"
              : "border-ink bg-ink text-white";
  const tone = active
    ? activeTone
    : "border-brand-200 bg-white text-ink-soft hover:border-brand-300 hover:bg-brand-50";
  return (
    <button
      onClick={onClick}
      className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-xs font-semibold transition ${tone}`}
    >
      {label}
      <span
        className={`rounded-full px-1.5 text-[10px] font-bold ${
          active ? "bg-white/25 text-white" : "bg-brand-100 text-brand-700"
        }`}
      >
        {count}
      </span>
    </button>
  );
}

// One labelled dropdown inside a filter flyout.
function FilterSelect({
  label,
  value,
  onChange,
  options,
  allLabel,
  title,
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  options: { value: string; label: string }[];
  allLabel: string;
  title?: string;
}) {
  return (
    <label className="block" title={title}>
      <span className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-ink-muted">
        {label}
      </span>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className={FILTER_SELECT_CLS}
      >
        <option value="">{allLabel}</option>
        {options.map((o) => (
          <option key={o.value} value={o.value}>
            {o.label}
          </option>
        ))}
      </select>
    </label>
  );
}

// Editable "records per page" — a button that turns into a number input.
function PageSizeEditor({
  value,
  max,
  onCommit,
}: {
  value: number;
  max: number;
  onCommit: (n: number) => void;
}) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(String(value));
  const inputRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    if (editing) {
      inputRef.current?.focus();
      inputRef.current?.select();
    }
  }, [editing]);

  function commit() {
    const n = Math.min(max, Math.max(1, parseInt(draft, 10) || value));
    onCommit(n);
    setDraft(String(n));
    setEditing(false);
  }

  if (editing) {
    return (
      <input
        ref={inputRef}
        type="number"
        min={1}
        max={max}
        value={draft}
        onChange={(e) => setDraft(e.target.value)}
        onBlur={commit}
        onKeyDown={(e) => {
          if (e.key === "Enter") commit();
          else if (e.key === "Escape") setEditing(false);
        }}
        className="w-16 rounded-lg border border-brand-400 bg-white px-2 py-1 text-xs font-bold text-ink outline-none"
        aria-label="Records to display per page"
      />
    );
  }
  return (
    <button
      type="button"
      onClick={() => {
        setDraft(String(value));
        setEditing(true);
      }}
      className="inline-flex items-center gap-1 rounded-lg border border-brand-300 bg-brand-50 px-2 py-1 text-xs font-bold text-brand-700 transition hover:border-brand-400 hover:bg-brand-100"
      title="Records to display per page — click to change"
    >
      {value}
      <ChevronDown size={11} className="text-brand-500" />
    </button>
  );
}